[target.x86_64-pc-windows-msvc]
rustflags = ["-Clink-arg=/FORCE:MULTIPLE"]
[target.i686-pc-windows-msvc]
rustflags = ["-Clink-arg=/FORCE:MULTIPLE"]
[target.i686-unknown-linux-gnu]
rustflags = ["-Clink-arg=-Wl,--allow-multiple-definition"]
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-Wl,--allow-multiple-definition"]
